### ISSUE TITLE
Environment variables inside the build script

### ISSUE THREAD

**Issue by skident** [mikefourie-zz/MSBuildExplorer#5]
Hello,
I tried to open make.proj, but MSBuildExplorer can't find Environment Variables which are used in build script. Is there any approach to do set variables in the program directly? Something like this:
my_path=c:\tmp\my_path.

P.S. It works fine when I start your project from the VS

**Comment by chris1248** [comment]
Uh, msbuildexplorer finds environment variables in the project files just fine. This program is for viewing project files, not editing environment variables. If you want to change environment variables, do it normally through windows. Besides you can't set an environment variable through the msbuild API, you set properties, not environment variables.
